packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@tanstack/react-query": ^5.59.15
  "@trpc/client": ^11.0.0-rc.477
  "@trpc/react-query": ^11.0.0-rc.477
  "@trpc/server": ^11.0.0-rc.477
  prettier: ^3.3.3
  tailwindcss: ^3.4.14
  typescript: ^5.6.3
  superjson: ^2.2.1
  zod: ^3.23.8
  styled-jsx: ^5.1.6
  lucide-react: ^0.462.0
  "@emotion/react": "11.11.1"
  "@emotion/styled": "11.11.0"
  "@emotion/cache": "11.11.0"
  "@mui/icons-material": "^6.1.9"
  "@mui/lab": "6.0.0-beta.9"
  "@mui/material": "^6.1.9"
  sonner: ^1.7.0
  tiny-invariant: ^1.3.3

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1